name: httpcli
version: 0.1.0.0
github: "dustinrohde/httpcli"
license: BSD3
author: "Dustin Rohde"
maintainer: "dustin.rohde@gmail.com"
copyright: "2020 Dustin Rohde"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/dustinrohde/httpcli#readme>

dependencies:
  - aeson == 1.4.7.1
  - base >= 4.7 && < 5
  - containers == 0.6.2.1
  - filepath == 1.4.2.1
  - mustache == 2.3.1
  - parsec == 3.1.14.0
  - optparse-applicative == 0.15.1.0
  - req == 3.2.0
  - text == 1.2.4.0
  - yaml == 0.11.4.0

library:
  source-dirs: src

executables:
  httpcli-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - httpcli

tests:
  httpcli-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - httpcli
